[workspace]
members = ["macros"]

[package]
name = "coreutils"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
description = "GNU's coreutils rewritten in rust"
repository = "https://github.com/morr0ne/coreutils"
readme = "README.md"
publish = false

[dependencies]
coreutils_macros = { version = "0.0.1", path = "./macros"}
clap = { version = "4.1.4", default-features = false, features = ["std", "help", "cargo"] }
libc = { version = "0.2.139", optional = true }
nix = { version = "0.26.2", default-features = false, features = ["term"], optional = true }
blake2 = { version = "0.10.6", optional = true }
hex = { version = "0.4.3", optional = true }
# static_args = "0.2.1"

[features]
arch = ["dep:libc"]
b2sum = ["dep:blake2", "dep:hex"]
basename = []
false = []
true = []
tty = ["dep:nix"]
uname = ["dep:libc"]
who = []
whoami = ["dep:libc", "dep:nix"]
yes = []

[[bin]]
name = "arch"
path = "bin/arch.rs"
required-features = ["arch"]

[[bin]]
name = "b2sum"
path = "bin/b2sum.rs"
required-features = ["b2sum"]

[[bin]]
name = "uname"
path = "bin/uname.rs"
required-features = ["uname"]

[[bin]]
name = "whoami"
path = "bin/whoami.rs"
required-features = ["whoami"]

[[bin]]
name = "yes"
path = "bin/yes.rs"
required-features = ["yes"]


[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.bloat]
inherits = "release"
strip = false
