#[cfg(feature = "arch")]
pub mod arch;
#[cfg(feature = "b2sum")]
pub mod b2sum;
#[cfg(feature = "base32")]
pub mod base32;
#[cfg(feature = "base64")]
pub mod base64;
#[cfg(feature = "basename")]
pub mod basename;
#[cfg(feature = "basenc")]
pub mod basenc;
#[cfg(feature = "cat")]
pub mod cat;
#[cfg(feature = "chcon")]
pub mod chcon;
#[cfg(feature = "chgrp")]
pub mod chgrp;
#[cfg(feature = "chmod")]
pub mod chmod;
#[cfg(feature = "chown")]
pub mod chown;
#[cfg(feature = "chroot")]
pub mod chroot;
#[cfg(feature = "cksum")]
pub mod cksum;
#[cfg(feature = "comm")]
pub mod comm;
#[cfg(feature = "cp")]
pub mod cp;
#[cfg(feature = "csplit")]
pub mod csplit;
#[cfg(feature = "cut")]
pub mod cut;
#[cfg(feature = "date")]
pub mod date;
#[cfg(feature = "dd")]
pub mod dd;
#[cfg(feature = "df")]
pub mod df;
#[cfg(feature = "dir")]
pub mod dir;
#[cfg(feature = "dircolors")]
pub mod dircolors;
#[cfg(feature = "dirname")]
pub mod dirname;
#[cfg(feature = "du")]
pub mod du;
#[cfg(feature = "echo")]
pub mod echo;
#[cfg(feature = "env")]
pub mod env;
#[cfg(feature = "expand")]
pub mod expand;
#[cfg(feature = "expr")]
pub mod expr;
#[cfg(feature = "factor")]
pub mod factor;
#[cfg(feature = "false")]
pub mod r#false;
#[cfg(feature = "fmt")]
pub mod fmt;
#[cfg(feature = "fold")]
pub mod fold;
#[cfg(feature = "groups")]
pub mod groups;
#[cfg(feature = "head")]
pub mod head;
#[cfg(feature = "hostid")]
pub mod hostid;
#[cfg(feature = "hostname")]
pub mod hostname;
#[cfg(feature = "id")]
pub mod id;
#[cfg(feature = "install")]
pub mod install;
#[cfg(feature = "join")]
pub mod join;
#[cfg(feature = "kill")]
pub mod kill;
#[cfg(feature = "link")]
pub mod link;
#[cfg(feature = "ln")]
pub mod ln;
#[cfg(feature = "logname")]
pub mod logname;
#[cfg(feature = "ls")]
pub mod ls;
#[cfg(feature = "md5sum")]
pub mod md5sum;
#[cfg(feature = "mkdir")]
pub mod mkdir;
#[cfg(feature = "mkfifo")]
pub mod mkfifo;
#[cfg(feature = "mknod")]
pub mod mknod;
#[cfg(feature = "mktemp")]
pub mod mktemp;
#[cfg(feature = "mv")]
pub mod mv;
#[cfg(feature = "nice")]
pub mod nice;
#[cfg(feature = "nl")]
pub mod nl;
#[cfg(feature = "nohup")]
pub mod nohup;
#[cfg(feature = "nproc")]
pub mod nproc;
#[cfg(feature = "numfmt")]
pub mod numfmt;
#[cfg(feature = "od")]
pub mod od;
#[cfg(feature = "paste")]
pub mod paste;
#[cfg(feature = "pathchk")]
pub mod pathchk;
#[cfg(feature = "pinky")]
pub mod pinky;
#[cfg(feature = "pr")]
pub mod pr;
#[cfg(feature = "printenv")]
pub mod printenv;
#[cfg(feature = "printf")]
pub mod printf;
#[cfg(feature = "ptx")]
pub mod ptx;
#[cfg(feature = "pwd")]
pub mod pwd;
#[cfg(feature = "readlink")]
pub mod readlink;
#[cfg(feature = "realpath")]
pub mod realpath;
#[cfg(feature = "rm")]
pub mod rm;
#[cfg(feature = "rmdir")]
pub mod rmdir;
#[cfg(feature = "runcon")]
pub mod runcon;
#[cfg(feature = "seq")]
pub mod seq;
#[cfg(feature = "sha1sum")]
pub mod sha1sum;
#[cfg(feature = "sha224sum")]
pub mod sha224sum;
#[cfg(feature = "sha256sum")]
pub mod sha256sum;
#[cfg(feature = "sha384sum")]
pub mod sha384sum;
#[cfg(feature = "sha512sum")]
pub mod sha512sum;
#[cfg(feature = "shred")]
pub mod shred;
#[cfg(feature = "shuf")]
pub mod shuf;
#[cfg(feature = "sleep")]
pub mod sleep;
#[cfg(feature = "sort")]
pub mod sort;
#[cfg(feature = "split")]
pub mod split;
#[cfg(feature = "stat")]
pub mod stat;
#[cfg(feature = "stdbuf")]
pub mod stdbuf;
#[cfg(feature = "stty")]
pub mod stty;
#[cfg(feature = "sum")]
pub mod sum;
#[cfg(feature = "sync")]
pub mod sync;
#[cfg(feature = "tac")]
pub mod tac;
#[cfg(feature = "tail")]
pub mod tail;
#[cfg(feature = "tee")]
pub mod tee;
#[cfg(feature = "test")]
pub mod test;
#[cfg(feature = "timeout")]
pub mod timeout;
#[cfg(feature = "touch")]
pub mod touch;
#[cfg(feature = "tr")]
pub mod tr;
#[cfg(feature = "true")]
pub mod r#true;
#[cfg(feature = "truncate")]
pub mod truncate;
#[cfg(feature = "tsort")]
pub mod tsort;
#[cfg(feature = "tty")]
pub mod tty;
#[cfg(feature = "uname")]
pub mod uname;
#[cfg(feature = "unexpand")]
pub mod unexpand;
#[cfg(feature = "uniq")]
pub mod uniq;
#[cfg(feature = "unlink")]
pub mod unlink;
#[cfg(feature = "uptime")]
pub mod uptime;
#[cfg(feature = "users")]
pub mod users;
#[cfg(feature = "vdir")]
pub mod vdir;
#[cfg(feature = "wc")]
pub mod wc;
#[cfg(feature = "who")]
pub mod who;
#[cfg(feature = "whoami")]
pub mod whoami;
#[cfg(feature = "yes")]
pub mod yes;
